### ISSUE TITLE
Design decision: Cloud database platform

### ISSUE THREAD

**Issue by shuchirinamdar** [aman-srivastava/SNA4Slack#8]
Identify a cloud-based platform to setting up the application database

**Comment by bateman** [comment]
A related note. Regardless of what free-tier cloud platform solution is identified, I think we should consider distributing a Docker-based version of SNA4Slack, in order to avoid vendor lock-in issues after the project is completed. Anyone interested could just grab the docker file from DockerHub and deploy/run it with close-to-zero effort. What do you think?

If you agree, please, create an entry in the backlog.

**Comment by shuchirinamdar** [comment]
Finalized on using Cassandra
